import pandas as pd
import sqlite3
from datetime import datetime
import sys
import io

# Cấu hình encoding cho Windows console
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

def find_column_fuzzy(df_columns, keywords):
    """
    Tìm cột có chứa bất kỳ keyword nào (case-insensitive, fuzzy matching)
    Trả về tên cột nếu tìm thấy, None nếu không
    """
    if isinstance(keywords, str):
        keywords = [keywords]
    
    for col in df_columns:
        col_lower = str(col).lower()
        for keyword in keywords:
            if keyword.lower() in col_lower:
                return col
    return None

def extract_issue_category(note):
    """
    Extract issue category từ Note
    Nếu không tìm thấy, trả về 'General'
    """
    if pd.isna(note) or note == '':
        return 'General'
    
    note_lower = str(note).lower()
    
    # Keywords để phân loại vấn đề
    keywords = {
        'wifi': 'Network/Wifi Issue',
        'internet': 'Network/Wifi Issue',
        'network': 'Network/Wifi Issue',
        'pinpad': 'Pinpad Issue',
        'payment': 'Payment Issue',
        'tip': 'Payment/Tip Issue',
        'charge': 'Payment Issue',
        'clockin': 'Clock In/Out Issue',
        'clock out': 'Clock In/Out Issue',
        'booking': 'Booking/Appointment Issue',
        'appointment': 'Booking/Appointment Issue',
        'app': 'App Issue',
        'password': 'Account/Password Issue',
        'passcode': 'Account/Password Issue',
        'login': 'Account/Password Issue',
        'block': 'Account/Blacklist Issue',
        'blacklist': 'Account/Blacklist Issue',
        'promotion': 'Promotion/Marketing',
        'menu': 'Menu/Price Issue',
        'price': 'Menu/Price Issue',
        'salary': 'Payroll Issue',
        'lương': 'Payroll Issue',
        'support': 'Support Request'
    }
    
    for keyword, category in keywords.items():
        if keyword in note_lower:
            return category
    
    return 'General'

def normalize_status(status):
    """
    Normalize status từ CSV sang database format
    Done -> Done
    Support/No Answer -> Pending
    Các giá trị khác -> Pending
    """
    if pd.isna(status):
        return 'Pending'
    
    status_str = str(status).strip()
    if status_str.lower() == 'done':
        return 'Done'
    elif status_str.lower() == 'no answer':
        return 'No Answer'
    else:
        return 'Pending'

def clean_db():
    """Xóa toàn bộ dữ liệu và tạo lại bảng tickets"""
    conn = sqlite3.connect('crm_data.db')
    c = conn.cursor()
    
    # Xóa bảng cũ
    c.execute('DROP TABLE IF EXISTS tickets')
    
    # Tạo lại bảng với schema mới nhất (including CID, Agent_Name, Support_Time, Caller_Info)
    c.execute('''
        CREATE TABLE tickets (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            Date TEXT NOT NULL,
            Salon_Name TEXT NOT NULL,
            Phone TEXT NOT NULL,
            Issue_Category TEXT NOT NULL,
            Note TEXT,
            Status TEXT NOT NULL DEFAULT 'Pending',
            Created_At TEXT NOT NULL,
            CID TEXT,
            Contact TEXT,
            Card_16_Digits TEXT,
            Training_Note TEXT,
            Demo_Note TEXT,
            Agent_Name TEXT,
            Support_Time TEXT,
            Caller_Info TEXT
        )
    ''')
    
    conn.commit()
    conn.close()
    print("✅ Đã xóa và tạo lại bảng tickets với schema mới nhất")

def map_csv_columns(df_columns):
    """
    Map các cột CSV vào database columns bằng fuzzy matching
    Trả về dictionary: {db_column: csv_column_name}
    Note: CSV is generated by main.py from Excel daily sheets (1, 2, 3, etc.) which have Name and CID columns
    """
    mapping = {}
    
    # Các cột cơ bản (exact match hoặc fuzzy match)
    exact_mapping = {
        'Date': ['Date'],
        'Salon_Name': ['Salon Name', 'Salon_Name'],
        'Phone': ['Phone'],
        'Note': ['Note'],
        'Status': ['Status'],
        'Agent_Name': ['Name'],  # Name column from Excel daily sheets -> Agent_Name in DB
        'CID': ['CID']  # CID column from Excel daily sheets -> CID in DB
    }
    
    for db_col, csv_patterns in exact_mapping.items():
        for pattern in csv_patterns:
            if pattern in df_columns:
                mapping[db_col] = pattern
                break
    
    # Các cột mới (fuzzy matching)
    fuzzy_mappings = {
        'Contact': ['Contact', 'Caller'],
        'Training_Note': ['Training'],
        'Demo_Note': ['Demo'],
        'Card_16_Digits': ['Card', '16']
    }
    
    for db_col, keywords in fuzzy_mappings.items():
        csv_col = find_column_fuzzy(df_columns, keywords)
        if csv_col and csv_col not in mapping.values():
            mapping[db_col] = csv_col
    
    return mapping

def safe_get_value(row, column_name, default=''):
    """
    Lấy giá trị từ row, nếu không có hoặc NaN thì trả về default
    """
    if column_name not in row.index:
        return default
    
    value = row[column_name]
    if pd.isna(value):
        return default
    
    # Chuyển thành string và strip
    value_str = str(value).strip()
    return value_str if value_str else default

def import_tickets_from_csv():
    """Import dữ liệu từ cleaned_tickets_history.csv vào database"""
    print("=" * 50)
    print("Import du lieu tu CSV vao database CRM")
    print("=" * 50)
    print()
    
    print("Dang doc file cleaned_tickets_history.csv...")
    
    try:
        # Đọc CSV
        df = pd.read_csv('cleaned_tickets_history.csv')
        print(f"✅ Đa doc {len(df)} dong tu CSV")
        print(f"   Cac cot co trong CSV: {', '.join(df.columns.tolist())}")
        print()
        
        # Làm sạch database
        print("Dang lam sach database...")
        clean_db()
        print()
        
        # Map các cột
        print("Dang map cac cot...")
        column_mapping = map_csv_columns(df.columns)
        print(f"   Cot duoc map: {column_mapping}")
        
        # CRITICAL: Ensure Name -> Agent_Name and CID -> CID mappings exist
        if 'Name' in df.columns and 'Agent_Name' not in column_mapping:
            column_mapping['Agent_Name'] = 'Name'
            print(f"   ✅ Fixed: Agent_Name now mapped to CSV column 'Name'")
        
        if 'CID' in df.columns and 'CID' not in column_mapping:
            column_mapping['CID'] = 'CID'
            print(f"   ✅ Fixed: CID now mapped to CSV column 'CID'")
        
        # Verify critical mappings
        if 'Agent_Name' in column_mapping:
            csv_col = column_mapping['Agent_Name']
            print(f"   ✅ Agent_Name mapped to CSV column: '{csv_col}'")
            if csv_col in df.columns:
                sample_value = df[csv_col].dropna().iloc[0] if len(df[csv_col].dropna()) > 0 else "N/A"
                print(f"      Sample value: '{sample_value}'")
            else:
                print(f"      ⚠️ WARNING: CSV column '{csv_col}' not found in dataframe!")
        else:
            print(f"   ❌ ERROR: Agent_Name mapping NOT found!")
        
        if 'CID' in column_mapping:
            csv_col = column_mapping['CID']
            print(f"   ✅ CID mapped to CSV column: '{csv_col}'")
            if csv_col in df.columns:
                sample_value = df[csv_col].dropna().iloc[0] if len(df[csv_col].dropna()) > 0 else "N/A"
                print(f"      Sample value: '{sample_value}'")
            else:
                print(f"      ⚠️ WARNING: CSV column '{csv_col}' not found in dataframe!")
        else:
            print(f"   ❌ ERROR: CID mapping NOT found!")
        print()
        
        # Kết nối database
        conn = sqlite3.connect('crm_data.db')
        c = conn.cursor()
        
        imported = 0
        skipped = 0
        
        print("Dang import du lieu...")
        
        for idx, row in df.iterrows():
            try:
                # Lấy các giá trị từ CSV (với mapping)
                date = safe_get_value(row, column_mapping.get('Date', 'Date'))
                salon_name = safe_get_value(row, column_mapping.get('Salon_Name', 'Salon Name'))
                phone = safe_get_value(row, column_mapping.get('Phone', 'Phone'))
                note = safe_get_value(row, column_mapping.get('Note', 'Note'))
                status = normalize_status(safe_get_value(row, column_mapping.get('Status', 'Status')))
                
                # Extract issue category từ Note
                issue_category = extract_issue_category(note)
                
                # Các cột mới (fuzzy matching)
                contact = safe_get_value(row, column_mapping.get('Contact', ''))
                card_16_digits = safe_get_value(row, column_mapping.get('Card_16_Digits', ''))
                training_note = safe_get_value(row, column_mapping.get('Training_Note', ''))
                demo_note = safe_get_value(row, column_mapping.get('Demo_Note', ''))
                
                # CRITICAL: Extract CID and Agent_Name using mapped column names
                cid_csv_col = column_mapping.get('CID', 'CID')
                agent_name_csv_col = column_mapping.get('Agent_Name', 'Name')
                
                cid = safe_get_value(row, cid_csv_col)
                agent_name = safe_get_value(row, agent_name_csv_col)
                
                # Debug first few rows
                if imported < 3:
                    print(f"   Row {idx+1}: CID column='{cid_csv_col}', value='{cid}', Agent_Name column='{agent_name_csv_col}', value='{agent_name}'")
                
                # Tạo Created_At từ Date và Time (nếu có)
                time_col = find_column_fuzzy(df.columns, ['Time'])
                if time_col and time_col in row.index and not pd.isna(row[time_col]):
                    try:
                        time_str = str(row[time_col]).split('.')[0]  # Bỏ phần microsecond
                        if ':' in time_str:
                            created_at = f"{date} {time_str}"
                        else:
                            created_at = f"{date} 00:00:00"
                    except:
                        created_at = f"{date} 00:00:00"
                else:
                    created_at = f"{date} 00:00:00"
                
                # Validate dữ liệu bắt buộc
                if not salon_name or not phone:
                    skipped += 1
                    continue
                
                # Chuyển None thành chuỗi rỗng cho các trường optional
                contact = contact if contact else ''
                card_16_digits = card_16_digits if card_16_digits else ''
                training_note = training_note if training_note else ''
                demo_note = demo_note if demo_note else ''
                note = note if note else ''
                
                # Insert vào database (including CID and Agent_Name)
                # CRITICAL: Ensure CID and Agent_Name are explicitly included in INSERT
                c.execute('''
                    INSERT INTO tickets (Date, Salon_Name, Phone, Issue_Category, Note, Status, Created_At,
                                        CID, Contact, Card_16_Digits, Training_Note, Demo_Note,
                                        Agent_Name, Support_Time, Caller_Info)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ''', (
                    date, 
                    salon_name, 
                    phone, 
                    issue_category, 
                    note, 
                    status, 
                    created_at,
                    cid if cid and cid.strip() else None,  # CID: use value if not empty, else None
                    contact if contact and contact.strip() else None, 
                    card_16_digits if card_16_digits and card_16_digits.strip() else None,
                    training_note if training_note and training_note.strip() else None, 
                    demo_note if demo_note and demo_note.strip() else None,
                    agent_name if agent_name and agent_name.strip() else None,  # Agent_Name: use value if not empty, else None
                    None,  # Support_Time
                    None   # Caller_Info
                ))
                
                imported += 1
                
                # Hiển thị progress mỗi 500 dòng
                if imported % 500 == 0:
                    print(f"  Da import {imported} tickets...")
                    
            except Exception as e:
                skipped += 1
                if skipped <= 10:  # Chỉ hiển thị 10 lỗi đầu tiên
                    print(f"  ⚠️ Loi o dong {idx + 2}: {str(e)}")
                continue
        
        conn.commit()
        conn.close()
        
        print(f"\n✅ Hoan thanh!")
        print(f"  - Da import: {imported} tickets")
        print(f"  - Da bo qua: {skipped} dong (du lieu khong hop le)")
        
        # Hiển thị thống kê
        conn = sqlite3.connect('crm_data.db')
        c = conn.cursor()
        c.execute('SELECT COUNT(*) FROM tickets')
        total_count = c.fetchone()[0]
        c.execute('SELECT COUNT(*) FROM tickets WHERE Status = "Done"')
        done_count = c.fetchone()[0]
        c.execute('SELECT COUNT(*) FROM tickets WHERE Status = "Pending"')
        pending_count = c.fetchone()[0]
        c.execute('SELECT COUNT(*) FROM tickets WHERE Status = "No Answer"')
        no_answer_count = c.fetchone()[0]
        c.execute('SELECT COUNT(*) FROM tickets WHERE Contact IS NOT NULL AND Contact != ""')
        contact_count = c.fetchone()[0]
        c.execute('SELECT COUNT(*) FROM tickets WHERE Card_16_Digits IS NOT NULL AND Card_16_Digits != ""')
        card_count = c.fetchone()[0]
        c.execute('SELECT COUNT(*) FROM tickets WHERE Training_Note IS NOT NULL AND Training_Note != ""')
        training_count = c.fetchone()[0]
        c.execute('SELECT COUNT(*) FROM tickets WHERE Demo_Note IS NOT NULL AND Demo_Note != ""')
        demo_count = c.fetchone()[0]
        conn.close()
        
        print(f"\n📊 Thong ke database:")
        print(f"  - Tong so tickets: {total_count}")
        print(f"  - Done: {done_count}")
        print(f"  - Pending: {pending_count}")
        print(f"  - No Answer: {no_answer_count}")
        print(f"  - Co Contact: {contact_count}")
        print(f"  - Co Card_16_Digits: {card_count}")
        print(f"  - Co Training_Note: {training_count}")
        print(f"  - Co Demo_Note: {demo_count}")
        
    except FileNotFoundError:
        print("❌ Khong tim thay file cleaned_tickets_history.csv")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Loi: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == '__main__':
    import_tickets_from_csv()
    
    print("\n" + "=" * 50)
    print("Hoan tat import du lieu!")
    print("=" * 50)
